web:
  build: .
  ports:
   - "8080:8080"
  links:
    - fake-intel
    - redis
  command: ./run.sh
  volumes:
    - .:/usr/src/app

# You can add other fake services using the same syntax as below but with different yaml files
fake-intel:
  image: quii/mockingjay-server:1.2
  volumes:
    - ./fakes:/fakes
# The path here is the container volume, NOT the local path
  command: -config=/fakes/fake-intel.yaml
  ports:
   - "9090:9090"

# You could also pull in other images for other system dependencies such as databases or whatevs! 
redis:
  image: redis
  ports:
    - "6379"
